Fix OS X compile error
Use of aggregate initializer causes compile error on OS X. Error is:

```
  CXX(target) Release/obj.target/spellchecker/src/transcoder_posix.o
../src/transcoder_posix.cc:17:28: error: expected expression
  two_byte_value.integer = {0x0102};
                           ^
1 error generated.
```

Another possibility is that it's not being compiled using -std=c++11 or greater